### ISSUE TITLE
Document relationship between Profiler object argument 'name' and profiling environment variable

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.utils#112]
Document the following relationship:

If the Profiler object is created as ```ru.Profiler(name='radical.entk.ResourceManager')```, the expected environment variable that needs to be set is ```RADICAL_ENTK_PROFILE=True```.

Also, does the name always need to be in this specific format "a.b.c" so that the format of the environment variable is A_B_PROFILE.

**Comment by andre-merzky** [comment]
This is documented by now.
