### ISSUE TITLE
create base class for session that is inherited by saga and rp

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.utils#113]

**Comment by andre-merzky** [comment]
Vivek and I discussed that again, and we agreed that, for the moment this is not needed.  Vivek basically needs the session **ID**, which can be obtained directly w/o problems, and the same holds for logger and profiler instances to use that ID.  The ID can also directly be used by RP.  Moving the session to utils is somewhat more work than I thought (I would need to disentangle the saga engine initialization from the session construction), and we don't see any semantic benefits for the time being.

Closing this tickets until new arguments arise.
