### ISSUE TITLE
Clean version 2 from legacy unused code

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.utils#143]
Hello @andre-merzky,

what do you think if we start cleaning version 2 of radical utils from any unused legacy code?

Giannis

**Comment by andre-merzky** [comment]
I am unsure about that.  On the one hand its good to remove code which is not used.  On the other hand that code captures quite a bit of tinkering.

I am certainly open for cleaning the code bit by bit though.  Let me go through RU tomorrow to check what I would also consider obsolete...

**Comment by andre-merzky** [comment]
I checked - its only the RU testing framework which is really obsolete.  There is some code which is not used in RCT, but *should* be used  - that code should be kept in place.
