### ISSUE TITLE
Command for latest version (stack) check?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#192]
`radical-stack` command displays information of current environments along with a python version and virtualenv. Maybe `ru` can proactively confirm if the stacks are outdated/updatable when the new release is available? This is similar to `pip`, e.g. `You are using pip version 9.0.1, however version 18.0 is available.`. The reference of the function is at https://github.com/pypa/pip/blob/898d1056494adc16e4f6836711b40eca25ae7202/src/pip/_internal/self_outdated_check.py#L160. This is asking for consideration, not a bug report.

**Comment by andre-merzky** [comment]
The pip implementation is rather involved and uses some pip external, that seems like overkill.  But the same information could be fetched by:
```
import radical.utils as ru
out, err, ret = ru.sh_callout('python -m pip search radical.pilot radical.utils')
print(out)
```
which results in
```
radical.utils (0.90.3)  - Utilities for RADICAL CybertoolsProjects
radical.pilot (0.90.1)  - The RADICAL pilot job framework
```
That could then be parsed for the version info.  I am not sure how stable that pip output format is, but it seems a much simpler approach than trying to use pip internals.  Would you like to take a crack at that?

**Comment by lee212** [comment]
This looks much better than I thought. I'll try with PR and ask your review.

**Comment by lee212** [comment]
Andre made changes and merged them. This issue can be closed.
