### ISSUE TITLE
error: The 'msgpack' distribution was not found and is required by radical.utils

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#214]
This error has seen during the readthedocs build for entk.

I am not certain about this error but here is some snapshots of attempting the installation:
```
Searching for msgpack-python
Reading https://pypi.org/simple/msgpack-python/
Downloading https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz#sha256=378cc8a6d3545b532dfd149da715abae4fda2a3adb6d74e525d0d5e51f46909b
Best match: msgpack-python 0.5.6
Processing msgpack-python-0.5.6.tar.gz
```

It looks fine for searching/installing `msgpack` during ru installation. but later while saga is installed:
```
msgpack-python 0.5.6 is already the active version in easy-install.pth

Installed /home/docs/checkouts/readthedocs.org/user_builds/radicalentk/envs/latest/lib/python3.7/site-packages/msgpack_python-0.5.6-py3.7-linux-x86_64.egg
error: The 'msgpack' distribution was not found and is required by radical.utils
```

This error blocks building API documentation for EnTK (radical-cybertools/radical.entk/issues/418) which I am trying to resolve.

**Comment by andre-merzky** [comment]
I don't understand this problem, unfortunately.  RU depends on `msgpack`, and specifies this in `setup.py`.  That module name is valid and resolves cleanly.  I do not know where the reference to `msgpack-python` comes from.  The pilot bootstrapper used that, but that's not relevant during doc build.  I cleaned it out anyway in radical-cybertools/radical.pilot/pull/2067, but I don't see how this is relevant...

**Comment by andre-merzky** [comment]
What is also surprising is that RP and RS builds on RTD work w/o that problem, while they use the same underlying RU dependencies...  *scratch*

**Comment by andre-merzky** [comment]
Ah - I see that RP uses the flag `use system packages` in `advanced settings` - maybe that makes a difference.  I would  have expected to be problematic when used like in RP instead of when unset like in RE - but who knows... :-P

**Comment by lee212** [comment]
I looked at the error messages again and probably this is not the problem causing EnTK doc build failure. I see the errors:
```
removing 'radical.utils-1.0.0' (and everything under it)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radicalentk/envs/latest/lib/python3.7/site-packages/radical.pilot-1.0.0-py3.7.egg/share/radical.pilot/examples/data_staging/io_staging_pipeline.py", line 22
    print "[Callback]: ComputePilot '%s' state: %s." % (pilot.uid, state)
                                                   ^
SyntaxError: invalid syntax
``` 
where rp generates syntax errors because of examples with missing parentheses of a print function in py3. I find those examples have been updated/fixed now, the error message of missing `msgpack` would be suppressed once the new release is published to PyPI.

This ticket can be closed.

**Comment by andre-merzky** [comment]
thx
