### ISSUE TITLE
Default values in Description/Munch classes

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.utils#245]
When class is inherited from `Description`/`Munch` classes, default values of types `list` and `dict` should be set in `__init__` methods (or certain changes should be made in that parent classes).

Example of error that might be encountered (class `ComputePilotDescription` is picked randomly):
```python
from radical.pilot import ComputePilotDescription

pilot_descr = ComputePilotDescription({'resource': 'resource_00'})
print(pilot_descr.input_staging)  # output: []
pilot_descr.input_staging.append('file_00.txt')
print(pilot_descr.input_staging)  # output: ['file_00.txt']

pilot_descr_01 = ComputePilotDescription({'resource': 'resource_01'})
print(pilot_descr_01.input_staging)  # output: ['file_00.txt'], but SHOULD be []
```

When attribute of type `list` or `dict` is not defined as input, then corresponding default value is assigned (attribute gets a reference to the object from `cls._defaults`). Thus if new object (in the same namespace) is created, and the same attribute is not defined as input, then this attribute shares a reference to the object from `cls._defaults` with the previous one.

If [this](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_pilot_description.py#L174) would be moved to `__init__` as:
```python
    def __init__(self, from_dict=None):

        ru.Description.__init__(self, from_dict=ComputePilotDescription._defaults)
        self[INPUT_STAGING] = []

        if from_dict:
            self.update(from_dict)
```
then such error (described above) wouldn't be encountered.

**Comment by andre-merzky** [comment]
Hi @mtitov : I added a unit test in the `feature/config_inheritance` branch which tries to reproduce this - but it seems to work in that specific case.  Can you have a look please if the issue persists in that branch or is it already addressed?  Not sure what branch you used?  Thanks!

**Comment by mtitov** [comment]
Hi @andre-merzky, it is mostly related to implementation of inherited classes (just here is better place to bring it up), if such inherited classes would have class attribute `_defaults` and that will be used for unset attributes
```python
class _TestDescrWithDefaults(ru.Description):

    _schema = {
        'i245': [str]
    }
    _defaults = {
        'i245': []
    }

    def __init__(self, from_dict=None):
        ru.Description.__init__(
            self, from_dict=_TestDescrWithDefaults._defaults)
        if from_dict:
            self.update(from_dict)

def test_description_with_defaults():
    td = _TestDescrWithDefaults()
    td.i245.append('foo')
    td = _TestDescrWithDefaults()
    assert (not td.i245), td.i245
``` 
this will gives an error

**Comment by mtitov** [comment]
Additional comment related to `test_description`: when `td.verify()` is used, then `td.i245` is "re-created", thus it becomes a different `list` object

**Comment by andre-merzky** [comment]
I added another test with your code, and still can't trigger it - can you have a look please?

```
 $ pytest -v tests/unittests/test_description.py 
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /home/merzky/radical/radical.utils.work/ve3/bin/python
cachedir: .pytest_cache
rootdir: /home/merzky/radical/radical.utils.work, inifile: setup.cfg
plugins: cov-2.9.0
collected 2 items                                                                                                                                                                          

tests/unittests/test_description.py::test_description PASSED                                                                                                                         [ 50%]
tests/unittests/test_description.py::test_inheritance PASSED                                                                                                                         [100%]

==================================================================================== 2 passed in 0.05s =====================================================================================

$ rs

  python               : 3.8.2
  pythonpath           : 
  virtualenv           : /home/merzky/radical/radical.utils.work/ve3

  radical.pilot        : 1.4.1
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0-v1.3.1-92-g62f33ce@feature-config_inheritance
```

BTW: the `if from_dict: self.update(from_dict)` is not needed - that's done internally in the Munch constructor.  It does not change the result though.

**Comment by mtitov** [comment]
@andre-merzky it does PASS if it is inside the method `test_inheritance`, it is FAILED if you will move class and test method outside of `test_inheritance`

**Comment by mtitov** [comment]
I guess having it inside function always gives a "new" `_TestDescrWithDefaults` class, thus it shouldn't be inside

**Comment by andre-merzky** [comment]
Oh boy, I hate Python...  What a mess of a language...   Thanks for tracking this down, I look into it.

**Comment by andre-merzky** [comment]
I pushed a fix (doing a deepcopy of the initialization dict in the Munch c'tor) - can you have a look if that works for you?

**Comment by mtitov** [comment]
@andre-merzky yes, that works! thank you! (looks like this was the "shortest" way to fix it 😄)

**Comment by mtitov** [comment]
Resolved with new coming updates (dev branch: `feature/config_inheritance`)

**Comment by andre-merzky** [comment]
thanks!
