### ISSUE TITLE
Extend set of parameters for MongoDB connection

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.utils#246]
Could the parameter `tlsAllowInvalidCertificates=True` be added to `MongoClient` at `misc.mongodb_connect`? ([here](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/misc.py#L103))

This parameter is required for connection to a dedicated MongoDB instance at LLNL (for Lassen).

p.s. that parameter was proposed to be used, and without it the following error appears:
```
pymongo.errors.ServerSelectionTimeoutError: xxxxxxx.llnl.gov:xxxxx: 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: 
self signed certificate in certificate chain (_ssl.c:1076)
```

**Comment by andre-merzky** [comment]
This sounds backward compatible, so I don't see an issue with it.

**Comment by mtitov** [comment]
@andre-merzky to have this parameter set with default value `True`? can we have a control over it through `RADICAL_PILOT_DBURL`?

**Comment by mturilli** [comment]
Our MongoDB is also configured to use that parameter when it is set so it should not create a problem. About the parameter, should we use an env RADICAL_PILOT_DBURL_TLS=True/False and a new parameter in the constructor?

**Comment by mtitov** [comment]
@mturilli such flag we can use with `RADICAL_PILOT_DBURL` by adding `ssl` to the URL as `"mongodb+ssl://..."` (it will be translated to `ssl` parameter at `MongoClient`, which is alias for `tls`).

Maybe scheme can be extended as `"mongodb+ssl+allowinvalidcerts://..."`? (just a random suggestion)

**Comment by mturilli** [comment]
Thanks. Then I think that would work as we would leave the users to specify the protocol they want to use. Our server has a valid certificate.

**Comment by andre-merzky** [comment]
I would like to avoid overloading the protocol field of the URL - this is not selecting a new protocol.  And env variable, or `~/.radical/utils/configs`, or if must be the query field of the URL (which we also use to overload some information on the SAGA layer when passing URLs).

I also would allow the `default=True`, but that's just me (if we allow to connect to hosts which need that, what difference does it make to set it by default?)

**Comment by mtitov** [comment]
@andre-merzky I like the idea to use query field, since it fits mongo-url definition ([options](https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options))

> I also would allow the default=True, but that's just me (if we allow to connect to hosts which need that, what difference does it make to set it by default?)

agree, but that should be used with precaution, official [docs](https://api.mongodb.com/python/current/api/pymongo/mongo_client.html) state the following "Think very carefully before setting this to True as that could make your application vulnerable to man-in-the-middle attacks."

**Comment by mturilli** [comment]
AFAIK, man in the middle is a problem when using it with self-signed certificates. It is not clear to me at the moment what it happens if we force TLS on a server that is not configured to manage it. Instead of testing that, I would make TLS an opt-in option.

**Comment by mtitov** [comment]
> man in the middle is a problem when using it with self-signed certificates

looks like this is the case for dedicated MongoDB instance at LLNL

> I would make TLS an opt-in option

it is opts now, so `RADICAL_PILOT_DBURL` can be either `"mongodb://..."` or `"mongodb+ssl://..."` if tls/ssl is configured at the server
