### ISSUE TITLE
mongodb_connect does not parse a password with a special character, `/`

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#268]
I wonder how radical utils manages mongodb authentication when a password has special characters in it. For example, I define `RADICAL_PILOT_DBURL` with info like :`mongodb://username:pass/word@hostname:port/dbname`, and note that password includes a forward slash (`/`).  The parsing won't be successful because the `pass/word` isn't escaped. pymongo has a URL parser, `unquote_plus` therefore it is valid to use a password like `'mongodb://username:' + urllib.parse.quote_plus('pass/word') + '@hostname:port/dbname'` in general, and assigning this encoded URI to `RADICAL_PILOT_DBURL` can have same behavior if there is a function to manage this. It can be done by replacing this line: https://github.com/radical-cybertools/radical.utils/blob/274e21274cb7d3f2fa7cf6957e9c8327bba41421/src/radical/utils/misc.py#L46 to `pwd = urllib.parse.unquote_plus(url.password)` as it yields the same string if there is no special character to replace.

BTW, this is related to the mongodb service deployed on LLNL Lassen with SSL.

**Comment by andre-merzky** [comment]
That sounds sensible - would you mind opening a RP?  Thanks!

**Comment by andre-merzky** [comment]
This is obsolete by now.
