### ISSUE TITLE
db_utils fails to create dataframes from json session file

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.utils#34]
RU 0.28
```
>>> import os
>>> import radical.pilot.utils as rpu
>>> import pandas as pd
>>> pd.set_option('display.width', 1000)
>>> cachedir = os.getcwd()
>>> db = 'mongodb://54.221.194.147:24242/mturilli_aimesexperiments'
>>> session = 'rp.session.ip-10-184-31-85.mturilli.016547.0001'
>>> s_frame, p_frame, u_frame = rpu.get_session_frames(db,session,cachedir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mturilli/Virtualenvs/RP-0.28/local/lib/python2.7/site-packages/radical/pilot/utils/db_utils.py", line 153, in get_session_frames
    docs = get_session_docs (db, sid, cachedir=cachedir)
  File "/home/mturilli/Virtualenvs/RP-0.28/local/lib/python2.7/site-packages/radical/pilot/utils/db_utils.py", line 87, in get_session_docs
    json_data['session'] = bson2json (list(db["%s"    % sid].find ()))
TypeError: string indices must be integers, not str
```

**Comment by andre-merzky** [comment]
get_session_docs should get, as first parameter, a db *instance*, not a URL.  You can get a mongodb handle like this:

```
mongo, db, dbname, cname, pname = ru.mongodb_connect (str(url))
```

see https://github.com/radical-cybertools/radical.utils/blob/master/src/radical/utils/misc.py#L67

**Comment by mturilli** [comment]
Thank you. Is this change documented somewhere?

**Comment by andre-merzky** [comment]
This is not a change, that was the same in the aimes branch.  Having said that, the utils are generally not well documented.  At this point, they are really just a code drop for the bin/*tools.  That should hopefully change once we move the semantics of those tools into utils, in a somewhat organized fashion...

**Comment by mturilli** [comment]
I have been using the code I pasted for all my experiments without a problem. Something has changed :) But this is unimportant, as I now know how to make it work again. 

OK for the documentation, we will wait for the move to utils then.

**Comment by andre-merzky** [comment]
> I have been using the code I pasted for all my experiments without a problem. Something has changed :) But this is unimportant, as I now know how to make it work again.

My apologies then -- I based this on the current code in the aimes branch.  But maybe that has changed while patching back-and-forth during the backporting phase...

> OK for the documentation, we will wait for the move to utils then.

At some point in the past, you voiced interest in starting to move parts of the tools into utils -- are you still interested in starting that?  Mark also mentioned similar things over the last week.  Lest discuss it on the call tonight who takes responsibility in this context...

Thanks, Andre.
