### ISSUE TITLE
Doctree is unwieldy and confusing

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.utils#375]
The documentation hierarchy is full of duplication and confusing nesting levels. It is also missing targets for package modules, including, simply `:py:mod:'radical.utils'`

I think it would simplify layout and maintenance to add docstrings to all modules (including package modules), and just use `automodule` for everything. The separate RST documents for subpackages could be removed. It could also help with #359, where classes are frequently referenced using their import aliases in parent classes. 

A minimal patch that would provide module targets and a more readable could just remove some duplication and replace some `automodule` directives with `py:module` directives.

**Comment by andre-merzky** [comment]
Many thanks for the PR, @eirrgang !  Can we close this ticket for now or do you think there are items unaddressed?

**Comment by eirrgang** [comment]
The issue is minimally resolved. I suggest adding actual module docstrings, but that should be a separate issue, and at the discretion of the core team, I think.
