### ISSUE TITLE
Activate `test_pubsub` or remove?

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.utils#388]
https://github.com/radical-cybertools/radical.utils/blob/9c82bfb0b93b41a8ab611951647d7581fbe142f7/src/radical/utils/zmq/pubsub.py#L534-L536

**Comment by andre-merzky** [comment]
The method itself is useful for testing and debugging - but I agree, the current code is, aehm, stupid.  I think we should re-enable the method but comment out its use in RP instead, with some useful comment to re-enable for debugging purposes.  I'll take care of it.
