### ISSUE TITLE
Url.get_path() throws exception

### ISSUE THREAD

**Issue by mehdisadeghi** [radical-cybertools/radical.utils#64]
Hi there,

According to this line of [documentation](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/url.py#L38) I should be able to do this:

    url = radical.utils.Url ("scheme://pass:user@host:123/path?query#fragment")

But surprisingly I get an error if I call `get_path` afterwards:

    >>> import radical.utils
    >>> url = radical.utils.Url ("scheme://pass:user@host:123/path?query#fragment")
    >>> url.get_path()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/W5/sade/workspace/radical.utils/src/radical/utils/url.py", line 427, in get_path
        (path, query) = path
    ValueError: too many values to unpack
    >>> 

Apparently changing [this line](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/url.py#L427) might help:

     (path, query) = path -> (path, query) = path.split('?')

But as I digged ;-) deeper into saga code I realized there is an underlying `_urlobj` object which comes from [radical.utils.contrib.urlparse25](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/contrib/urlparse25.py) and it seems that saga is using its own url parsers according to some standards that I'm not familiar with. Therefore I don't know where should be changed to fix this behaviour. 

Anyway, here is an example of saga.Url which returns weired result:

    >>> from saga import Url
    >>> u2 = Url ("scheme://pass:user@host:123/path?query#fragment")
    >>> u2._urlobj
    ('scheme', 'pass:user@host:123', '/path?query#fragment', '', '', '')
    >>> u2.get_query()
    'query#fragment'
    >>> u2.get_fragment()
    ''
    >>> u2.get_username()
    'pass'
    >>> u2.get_password()
    'user'

I am not sure if I am using the correct string, but that is from previous example, and there is the same exception here for calling `u2.get_path()`.

I am just trying to pass some ssh options to the job service, specifically `"StrictHostKeyChecking=no"`.

**Comment by andre-merzky** [comment]
Yes, you should be able to do this, this is  an error indeed.  

The underlying urlparse is quite a mess -- but IIRC, Ole could not find a better / working URL parser in python, so copied this one and adapted to our needs.  We have a long standing item to revisit that approach (see #30), but I have no idea when we'll get around actually doing so.

`pass:user@host` should really be `user:pass@host` I believe (https://tools.ietf.org/html/rfc3986, section 3.2.1) -- but the query/fragment parsing is clearly wrong.

#66 addresses this now -- but note that the urlparse module only allows fragments on a well defined set of schemas.  I assume that this set is aligned with the RFCs, but it does not help us as we do invent new schemas in SAGA/RP... :/  Not sure how to cleanly handle this -- we could just turn this check off I guess?

**Comment by mehdisadeghi** [comment]
I think if the underlying module is supposed to return proper values for path and query it is better to return it directly and let the underlying module to be responsible for parsing and throwing exceptions if necessary.

**Comment by mehdisadeghi** [comment]
@andre-merzky Hi Andre! I was just looking at open issues that I am involved in and reached out to this one. Shall we close this issue, since there is a merged PR for this?

**Comment by mehdisadeghi** [comment]
BTW, I read the PR, it says that this issue is fixed. Therefore I close this issue, feel free to reopen if something is wrong.

**Comment by andre-merzky** [comment]
thanks Mehdi - this should have been closed after the PR merge indeed...
