### ISSUE TITLE
RU/devel: setting the verbose to info also prints REPORT level msgs

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.utils#67]
Example:

```
2015-12-10 19:05:04,340: radical.enmd.Engine : MainProcess                     : MainThread     : INFO    :  > Loaded kernel plug-in 'misc.diff' from radical.ensemblemd.kernel_plugins.misc.diff

================================================================================
 EnsembleMD (0.3.6-86-g55ae40c)                                                 
================================================================================
```
"EnsembleMD (0.3.6-86-g55ae40c) " is from the REPORT level.

**Comment by andre-merzky** [comment]
Could you please show the output of: `env | rep VERBOSE`?  Thanks!

**Comment by vivek-bala** [comment]
```
$ env | grep VERBOSE
RADICAL_ENMD_VERBOSE=info
```

**Comment by vivek-bala** [comment]
I saw the same with RADICAL_PILOT_VERBOSE=info.

**Comment by andre-merzky** [comment]
And could you please show what logger is used to report that line?  Thanks!

**Comment by vivek-bala** [comment]
https://github.com/radical-cybertools/radical.ensemblemd/blob/master/src/radical/ensemblemd/exec_plugins/plugin_base.py#L35-L37

line 35 if for the regular logger. line 37 is for the report level.

This setup was working a month back.

**Comment by andre-merzky** [comment]
Vivek, this should be solved by now.  Please re-open if that is still a problem!
