### ISSUE TITLE
Error 'logging handlers already registered.'

### ISSUE THREAD

**Issue by joanlopez** [radical-cybertools/radical.utils#81]
Good afternoon mates,

As probably you already know, we (as BSC-ES) are using your SAGA library for our Autosubmit tool (https://earth.bsc.es/gitlab/es/autosubmit).

Since the last release of the radical.utils library (0.41) we have the next error:
_'logging handlers already registered.'_

We've researched about this issue and we've found that comes from the next source file:
_stdlib_fixer.py_

Do you know what could be producing this error?

We are also using the _logging_ Python library.

Could be due to an incompatibility?

Which could be the correct way to solve it?

Many thanks!

**Comment by andre-merzky** [comment]
Hi Joan, 

you certainly are on the right track here.  Let me explain the details:

the native python logging library is no safe to use in mixed multiprocess/multithreaded environments.  As an aside, that holds for several parts of python's standard library modules, but we have specifically been badly bitten by the logging module.  What happens is that any log handler which is active in a multithreaded process will acquire a lock - but if at that point the process forks, only the lock ownership of the `MainThread` is inherited, and locks in other threads are never cleaned.

The `stdlib_fixer` monkeypatches the logging module, making sure that the locks are released after fork.  That only works if the `stlib_fixer` is loaded *before* the logging module.

I can't judge if that fix is relevant for your environment.  If it is, I can only recommend to  use the same approach -- it resolved a huge amount of pain for us.  If it is not, I see two options: if you can, load `radical.utils` (or, in your case, `saga`) before the logging module.  If that is not possible (or cumbersome), I'd be happy to change utils in a way which makes patching optional, or at least removes the message.

Let me know what you think.  Either way, I think this should be easy to resolve.

Best, Andre.

**Comment by joanlopez** [comment]
Many thanks @andre-merzky 

I've changed the order of the imports (putting saga before the logger) and everything works now.
Although I think that I would need some classes about the Python import mechanism =)

Best,

**Comment by andre-merzky** [comment]
> Although I think that I would need some classes about the Python import mechanism =)

Don't go there if you can avoid it :P

The key point here is: any python interpreter instance will only load any given module once -- later calls to `import module` will fetch the module from the cache of loaded modules.

So, if `radical.utils` loads `logging` *first* and patches it, then all later imports from your own code (in the same process) will return the patched module instance, the fixer will not run again.

Best, Andre.

**Comment by joanlopez** [comment]
Hi @andre-merzky ,

I've recently seen that the problem persists with one automated test that we have.
However, in this case, the solution of moving the _import saga_ does not work.

Any recommendation?
Any better solution (not only for this test, also for all our system) than moving the _import saga_?

Thanks :)

**Comment by andre-merzky** [comment]
Doh!  My guess would be that the testing framework is pulling logging earlier than that.  How are you invoking the tests?

Either way, I think this calls for plan-B.  Let me implement a toggle to enable/disable the log fixer...

**Comment by andre-merzky** [comment]
Would you mind giving the branch `fix/81_logfix` a try?  With this branch, you can set the env variable `RADICAL_UTILS_NOATFORK` to disable the log patching.  Lets see how far that gets you, and once that works out, we can try to improve the usability for that setting...

Thanks, Andre.

**Comment by joanlopez** [comment]
Many thanks!

I've tested it and it works fine!

Are you planning to add this feature on the next release?
When?

Best,

**Comment by andre-merzky** [comment]
Great!

> Are you planning to add this feature on the next release?

Yes, at least some version of it.  Is it acceptable to you to have the env setting around?  If that would be the case, it would make our life simpler, as we can then leave the default as is (fix enabled).  Otherwise I would need to check what logic causes the least pain for all involved.

Either way, yes, it will go into release then.

Thanks, Andre.

**Comment by joanlopez** [comment]
At least by the moment it's enough.

We've added a chunk of code that sets this env variable (_os.environ_) for the test suite.

Thank you!

**Comment by andre-merzky** [comment]
Great, then we can keep it as is for now.

Thanks!
